databases:
  - name: postgres
    ipAllowList: []
    databaseName: rails_template
    user: rails_template
    plan: free

services:
  - type: web
    plan: free
    name: rails_template
    env: ruby
    buildCommand: "./render_build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
